codecov:
  fixes:
    - "::frontend/"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
      frontend:
        target: auto
        flags:
          - frontend
    patch:
      default:
        target: auto

flags:
  frontend:
    paths:
      - frontend/docs/components/
      - frontend/docs/.vitepress/theme/components/
    carryforward: false

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
