coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
      frontend:
        target: auto
        flags:
          - frontend
      backend:
        target: auto
        flags:
          - backend
    patch:
      default:
        target: auto

flags:
  frontend:
    paths:
      - frontend/
    carryforward: true
  backend:
    paths:
      - backend/
    carryforward: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
